import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import {
    MatDialogModule,
    MatButtonModule,
    MatInputModule,
    MatAutocompleteModule,
    MatTooltipModule,
    MatCheckboxModule,
    MatButtonToggleModule,
    MatDatepickerModule,
    MatNativeDateModule,
    MatSelectModule,
    MatSnackBarModule,
    MatCardModule,
    MatIconModule,
    MatExpansionModule,
    MatProgressSpinnerModule,
    MatChipsModule,
    MatRadioModule,
    MatListModule,
    MatProgressBarModule,
    MatMenuModule,
    MatSlideToggleModule,
    MatBadgeModule,
    MatRippleModule,
    MatTreeModule,
    MatTableModule,
    MatSidenavModule,
    MatToolbarModule
} from '@angular/material';

import { CdkTableModule } from '@angular/cdk/table';

@NgModule({
    declarations: [],
    imports: [
        CommonModule,
        MatDialogModule,
        MatButtonModule,
        MatInputModule,
        MatAutocompleteModule,
        MatTooltipModule,
        MatButtonToggleModule,
        MatDatepickerModule,
        MatCheckboxModule,
        MatNativeDateModule,
        MatSelectModule,
        MatSnackBarModule,
        MatCardModule,
        MatIconModule,
        MatExpansionModule,
        MatProgressSpinnerModule,
        MatChipsModule,
        MatRadioModule,
        MatListModule,
        MatProgressBarModule,
        MatMenuModule,
        MatSlideToggleModule,
        MatBadgeModule,
        MatRippleModule,
        MatTreeModule,
        MatTableModule,
        CdkTableModule,
        MatSidenavModule,
        MatToolbarModule
    ],
    exports: [
        MatDialogModule,
        MatButtonModule,
        MatInputModule,
        MatAutocompleteModule,
        MatTooltipModule,
        MatButtonToggleModule,
        MatDatepickerModule,
        MatCheckboxModule,
        MatNativeDateModule,
        MatSelectModule,
        MatSnackBarModule,
        MatCardModule,
        MatIconModule,
        MatExpansionModule,
        MatProgressSpinnerModule,
        MatChipsModule,
        MatRadioModule,
        MatListModule,
        MatMenuModule,
        MatProgressBarModule,
        MatSlideToggleModule,
        MatBadgeModule,
        MatRippleModule,
        MatTreeModule,
        MatTableModule,
        CdkTableModule,
        MatSidenavModule,
        MatToolbarModule
    ]
})
export class MaterialModule {}
